[package]
name = "hajiman"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
roots = "=0.0.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
